## Matriz de confusión

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn import neural_network, datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

np.random.seed(4)

X, y = datasets.load_wine(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
# Scaling data
scaler = StandardScaler() 
scaler.fit(X_train)  
X_train = scaler.transform(X_train)  
X_test = scaler.transform(X_test)  

modelo = neural_network.MLPClassifier(
        hidden_layer_sizes=(10),
        activation='relu',
        learning_rate_init=0.001,
        max_iter=100,
        solver='sgd'
        )

modelo.fit(X_train,y_train)

y_pred = modelo.predict(X_test)

CM = confusion_matrix(y_test,y_pred)

print("Matriz de confusión")
print(CM)

print("Score")
print(modelo.score(X_test, y_test))

print(" Informe ")
print(classification_report(y_test, y_pred))

Matriz de confusión
[[10  0  0]
 [ 2  8  3]
 [ 0  0 13]]
Score
0.8611111111111112
 Informe 
              precision    recall  f1-score   support

           0       0.83      1.00      0.91        10
           1       1.00      0.62      0.76        13
           2       0.81      1.00      0.90        13

    accuracy                           0.86        36
   macro avg       0.88      0.87      0.86        36
weighted avg       0.89      0.86      0.85        36



/Users/ivan/anaconda3/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:684: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(


In [2]:
y_test

array([2, 2, 0, 0, 1, 2, 0, 1, 0, 1, 1, 0, 2, 2, 0, 1, 0, 1, 1, 2, 1, 2,
       1, 2, 0, 2, 1, 1, 2, 2, 0, 1, 0, 1, 2, 2])

In [3]:
y_pred

array([2, 2, 0, 0, 1, 2, 0, 2, 0, 1, 1, 0, 2, 2, 0, 1, 0, 0, 1, 2, 1, 2,
       0, 2, 0, 2, 2, 1, 2, 2, 0, 2, 0, 1, 2, 2])

In [4]:
[y_test; y_pred]

SyntaxError: invalid syntax (3796247628.py, line 1)